name: Build and Test libft_gl

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_lib:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq build-essential gcc make

      - name: Build library
        run: |
          make
          make clean

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libft_gl
          path: libft_gl.a

  test_lib:
    runs-on: ubuntu-latest
    needs: build_lib

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq build-essential gcc make

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: libft_gl

      - name: Run tests
        run: |
          make test
          ./a.out

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: a.out

  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Setup dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq wget

      - name: Download safety
        run: wget https://github.com/safety-cli/safety/releases/download/v2.3.4/safety

      - name: Make safety executable
        run: chmod +x safety

      - name: Run security scan
        run: ./safety check
        continue-on-error: true
